# Generated by Django 6.0.6 on 2026-06-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskflag',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
